[workspace]
resolver = "2"
members = [
    "connectors/template",
    "connectors/whoop4",
    "crates/whoop-protocol",
]

[workspace.package]
edition = "2021"
rust-version = "1.96"
publish = false

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
